version: '2.1'
#
volumes:
    sense-data:
    dashboard-data:
    iaq-data:
    browser-settings:
    loudml-data:
#
services:
#
  influxdb:
    restart: always
    build: ./influx
    volumes:
      - 'sense-data:/var/lib/influxdb'
#
# LoudML engine works but Grafana conflicts and bugs not yet resolved
#  loudml:
#    restart: always
#    build: ./loudml
#    volumes:
#      - loudml-data:/var/lib/loudml
#    ports:
#      - 8077:8077
#    depends_on:
#      - influxdb
#
  dashboard:
    restart: always
    build: ./dashboard
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
#
  iaq:
    restart: on-failure
    build: ./iaq
    privileged: true
    volumes:
        - 'iaq-data:/data/my_data'
#
  connector:
    restart: always
    image: balenablocks/connector
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
#
  mqtt:
    restart: always 
    build: ./mqtt
    ports:
      - "1883:1883" # main database device needs this to allow remote connections from other sensors
#
# Configuration conflicts not yet resolved
#  wifi-connect:
#    restart: always
#    image: balenablocks/wifi-connect:armv7hf
#    network_mode: host
#    privileged: true
#    labels:
#      io.balena.features.dbus: "1"
#      io.balena.features.firmware: "1"
#    environment:
#      PORTAL_SSID: WHAQM Connect
#      PORTAL_LISTENING_PORT: 8080
#      ACTIVITY_TIMEOUT: 120
#
  browser:
    image: balenablocks/browser
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
      - '5011'
      - '35173'
    environment:
      KIOSK: 1
      LAUNCH_URL: "http://dashboard.local" # Force browser block to find only the dashboard w/o modifying its code
    volumes:
      - 'browser-settings:/data' # Only required if using PERSISTENT flag (see below)
