version: '2.1'
#
volumes:
    sense-data:
    dashboard-data:
    iaq-data:
    browser-settings:
#
services:
#
  influxdb:
    restart: always
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    # build: ./influx
    volumes:
      - 'sense-data:/var/lib/influxdb'
    ports:
      - 8086:8086 # Enable this for remote testing
#
  dashboard:
    restart: always
    build: ./dashboard
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
#
  iaq:
    restart: on-failure
    build: ./iaq
    privileged: true
    volumes:
        - 'iaq-data:/data/my_data'
#
  zeroconf:
    restart: always
    image: bh.cr/william_love/simple-zeroconf-arm7hf
    network_mode: host
    environment:
      ZEROCONF_SERVICE_PORT: 80
      ZEROCONF_SERVICE_TYPE: "_balenair"
      ZEROCONF_SERVICE_DESCRIPTION: "balenAir Dashboard Service"
    labels:
      io.balena.features.supervisor-api: '1'
#
  connector:
    restart: always
    image: bh.cr/balenablocks/connector-armv7hf
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    privileged: true
#
  mqtt:
    restart: always 
    build: ./mqtt
    ports:
      - "1883:1883" # main database device needs this to allow remote connections from other sensors
#
  wifi-connect:
    restart: always
    image: bh.cr/balenablocks/wifi-connect-armv7hf
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
    environment:
      PORTAL_SSID: "WHAQM Connect"
      PORTAL_LISTENING_PORT: 8080
      ACTIVITY_TIMEOUT: 120
#
  browser:
    restart: always
    image: bh.cr/balenablocks/browser-armv7hf
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
      - '5011'
      - '35173'
    environment:
      TZ: EST
      KIOSK: 1
    volumes:
      - 'browser-settings:/data' # Only required if using PERSISTENT flag
