version: '2.1'

services:
  connector:
    image: balenablocks/connector:latest
    restart: always
    labels:
      io.balena.features.balena-api: '1'    # necessary to discover services
      io.balena.features.supervisor-api: 1  # necessary to discover services in local mode
    privileged: true # necessary to change container hostname
    ports:
      - "8080" # only necessary if using ExternalHttpListener (see below)