{
 "title": "Main Summary Page",
 "tags": [ "Main" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "allLocation",
    "query": "SHOW TAG values  with KEY  = \"topic\""
   },
   {
    "name": "locations",
    "label": "Default Locations To View",
    "query": "SHOW TAG values  with KEY  = \"topic\""
   }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Measurements Across All Locations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Air Quality Indexes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"IAQ\") FROM \"mqtt_consumer\" WHERE $timeFilter GROUP BY time($__interval), \"topic\" fill(none)",
     "select": [
      [
       { "params": [ "IAQ" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2 (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Volatile Organic Compounds (ppb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "TVOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$locations Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "locations" },
  {
   "title": "Tempurature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT ((\"temperature\" * 1.8) + 32) FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Humidty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"humidity\"  FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "IAQ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "IAQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"IAQ\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter",
     "select": [
      [
       { "params": [ "IAQ" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TVOC (ppb)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"TVOC\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter",
     "select": [
      [
       { "params": [ "TVOC" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2 (ppm)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"co2\") FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Small Particles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"particles 03um\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Medium Particals ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"particles 10um\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter"
    }
   ]
  },
  {
   "title": "Large Particles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"particles 50um\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter"
    }
   ]
  },
  { "title": "$locations Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tempurature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT ((\"temperature\" * 1.8) + 32) FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Humidty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"humidity\"  FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "IAQ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "IAQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"IAQ\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter",
     "select": [
      [
       { "params": [ "IAQ" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TVOC (ppb)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"TVOC\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter",
     "select": [
      [
       { "params": [ "TVOC" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2 (ppm)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"co2\") FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "co2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Small Particles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"particles 03um\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Medium Particals ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"particles 10um\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter"
    }
   ]
  },
  {
   "title": "Large Particles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT \"particles 50um\" FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /.*$locations$/) AND  $timeFilter"
    }
   ]
  }
 ]
}